<?php
/**
 * composerize.php - Helper functions for the Composerize Unraid Plugin.
 *
 * This file contains the backend logic for finding Docker templates,
 * converting them to docker run commands, and installing compose files.
 *
 * PHP version 7.4+
 */

// Use strict types for better code quality and error detection.
declare(strict_types=1);

// --- Constants ---
// Define constants for directory paths to avoid magic strings and for easier maintenance.
define('DOCKER_TEMPLATE_DIRECTORY', '/boot/config/plugins/dockerMan/templates-user/');
define('COMPOSE_DIRECTORY', '/boot/config/plugins/compose.manager/projects/');

// It's best practice to include dependencies at the top of the file.
// This ensures that all necessary code is loaded before execution begins.
require_once '/usr/local/emhttp/plugins/dynamix.docker.manager/include/DockerClient.php';

/**
 * Validates a given string to see if it's a non-empty YAML string.
 *
 * NOTE: This is a basic check. True YAML validation would require a server-side
 * parsing library. Since the YAML is generated by the frontend, this is
 * generally safe enough for this plugin's purpose.
 *
 * @param string|null $yamlString The YAML string to validate.
 * @return bool True if the string is not null or empty, false otherwise.
 */
function isValidYaml(?string $yamlString): bool
{
    return !empty($yamlString);
}

/**
 * Installs a Docker Compose stack to the disk.
 *
 * This function creates a dedicated directory for the project and writes the
 * docker-compose.yml file and a 'name' file for the Compose Manager plugin.
 *
 * @param string $name    The name of the Docker Compose stack.
 * @param string $compose The Docker Compose YAML configuration as a string.
 * @param bool   $force   If true, any existing stack with the same name will be overwritten.
 *
 * @return bool True on success.
 * @throws Exception if the directory cannot be created or files cannot be written.
 */
function installCompose(string $name, string $compose, bool $force): bool
{
    $composeProjectDirectory = COMPOSE_DIRECTORY . $name;
    $composeYamlFilePath = $composeProjectDirectory . '/docker-compose.yml';
    $composeNameFilePath = $composeProjectDirectory . '/name';

    // Check if the project directory or files exist and if we should abort.
    if (!$force && (file_exists($composeProjectDirectory) || file_exists($composeYamlFilePath))) {
        // Returning false indicates a conflict (stack exists), which the API handles.
        return false;
    }

    // Create the project directory recursively if it doesn't exist.
    // The @ suppresses warnings on failure, which we handle manually.
    if (!is_dir($composeProjectDirectory) && !@mkdir($composeProjectDirectory, 0755, true)) {
        throw new Exception("Failed to create project directory: {$composeProjectDirectory}");
    }

    // Use file_put_contents for a more concise and safer way to write files.
    // It returns false on failure, which we can check directly.
    $nameWritten = file_put_contents($composeNameFilePath, $name);
    $yamlWritten = file_put_contents($composeYamlFilePath, $compose);

    if ($nameWritten === false || $yamlWritten === false) {
        // If writing failed, throw an exception to be caught by the API handler.
        throw new Exception("Failed to write compose files to disk for stack: {$name}");
    }

    return true;
}

/**
 * Scans the user templates directory for Docker XML templates and converts them
 * into an array of 'docker run' commands.
 *
 * @return array An associative array mapping the template name to its command string.
 * Example: ['Plex' => 'docker run ...']
 */
function getDockerTemplateList(): array
{
    $dockerTemplates = [];
    // Use glob to find all user-created Docker template XML files.
    $files = glob(DOCKER_TEMPLATE_DIRECTORY . '*.xml');

    if ($files === false) {
        // Handle the case where glob fails to read the directory.
        error_log('Composerize Plugin: Failed to read Docker template directory.');
        return [];
    }

    foreach ($files as $file) {
        try {
            // xmlToCommand is a legacy function from Unraid's Docker Manager.
            // It returns an array: [0 => command, 1 => name].
            $info = xmlToCommand($file, false);

            if (!is_array($info) || empty($info[0]) || empty($info[1])) {
                // Skip this template if the function returns invalid data.
                error_log("Composerize Plugin: Failed to parse template file: {$file}");
                continue;
            }

            // The command from xmlToCommand is a 'docker create' command.
            // We replace it with 'docker run' to be compatible with the composerize library.
            $command = str_replace(
                '/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create',
                'docker run',
                $info[0]
            );
            $name = $info[1];

            // Add the processed template to our list.
            $dockerTemplates[$name] = $command;
        } catch (Exception $e) {
            // Catch any errors during the parsing of a single file and log it.
            error_log("Composerize Plugin: Error processing template {$file}: " . $e->getMessage());
        }
    }

    // Sort the templates alphabetically by name for a better user experience.
    ksort($dockerTemplates);

    return $dockerTemplates;
}
